// Generated by CoffeeScript 1.6.3
var cli, command, exec, fs, paramater, print, run, runner, spawn, _ref;

require('colors');

print = require("util").print;

_ref = require("child_process"), exec = _ref.exec, spawn = _ref.spawn;

fs = require("fs");

cli = process.argv.slice(2);

process.stdin.resume();

command = cli[0];

paramater = cli.slice(1);

runner = {};

(run = function() {
  if (runner != null) {
    if (typeof runner.kill === "function") {
      runner.kill();
    }
  }
  runner = spawn(command, paramater);
  process.stdin.pipe(runner.stdin);
  runner.stdout.pipe(process.stdout);
  return runner.stderr.pipe(process.stderr);
})();

paramater.forEach(function(item) {
  var stat;
  if (fs.existsSync(item)) {
    stat = fs.statSync(item);
    if (!stat.isDirectory()) {
      return fs.watchFile(item, {
        interval: 100
      }, function(curr, prev) {
        print("\n\nRestarting...\n\n".blue);
        return run();
      });
    }
  }
});
